---

- name: Update server field in component kubeconfigs
  lineinfile:
    dest: "{{ kube_config_dir }}/{{ item }}"
    regexp: '^    server: https'
    line: '    server: {{ kube_apiserver_endpoint }}'
    backup: yes
  with_items:
    - admin.conf
    - controller-manager.conf
    - kubelet.conf
    - scheduler.conf
  notify:
    - "Master | Restart kube-controller-manager"
    - "Master | Restart kube-scheduler"
    - "Master | reload kubelet"

- name: Update etcd-servers for apiserver
  lineinfile:
    dest: "{{ kube_config_dir }}/manifests/kube-apiserver.yaml"
    regexp: '^    - --etcd-servers='
    line: '    - --etcd-servers={{ etcd_access_addresses }}'
  when: not etcd_kubeadm_enabled | default(false)

- name: Add custom env settings to apiserver
  vars:
    block:
      env: "{{ apiserver_custom_env }}"
  blockinfile:
    path: "{{ kube_config_dir }}/manifests/kube-apiserver.yaml"
    marker: "# {mark} CUSTOM ENV"
    insertbefore: "volumeMounts:"
    block: "{{ block |to_nice_yaml( indent=2, width=3000) |indent(width=4, indentfirst=True) }}"
  when: apiserver_custom_env
